/* Copyright (c) 2026, ApeCloud Inc Holding Limited. */

#ifndef SQL_REMOTE_COMMIT_STARTUP_COORDINATOR_INCLUDED
#define SQL_REMOTE_COMMIT_STARTUP_COORDINATOR_INCLUDED

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "sql/remote_commit/local_install.h"
#include "sql/remote_commit/materializer.h"
#include "sql/remote_commit/recovery.h"
#include "sql/remote_commit/snapshot_publisher.h"
#include "sql/remote_commit/startup_server.h"

namespace wesql::remote_commit {

inline constexpr size_t kStartupBootstrapPreflightMaxBytes =
    kMaxCanonicalGtidBytes + 64 * 1024;
inline constexpr size_t kStartupWorkerRequestMaxBytes =
    kRecoveryManifestBytesMax;
inline constexpr size_t kStartupWorkerEvidenceMaxBytes =
    kSnapshotManifestMaxBytes + 64 * 1024 * 1024;
inline constexpr size_t kStartupRestartProofMaxBytes =
    kMaxCanonicalGtidBytes + kHeadMaxBytes + kWriterEpochMaxBytes +
    kLocalInstallMarkerMaxBytes + 64 * 1024;

enum class StartupCoordinatorRoute : uint8_t {
  BOOTSTRAP,
  TAKEOVER,
};

enum class StartupCoordinatorState : uint8_t {
  STARTING,
  INITIALIZING,
  RECOVERING,
  WORKER_REQUIRED,
  SNAPSHOT_PUBLISHED,
  ROOT_INSTALLED,
  RESTART_REQUIRED,
  POST_ENGINE_VERIFICATION_REQUIRED,
  ACTIVATED,
  FAILED_CLOSED,
  FENCED,
};

enum class StartupCoordinatorOutcome : uint8_t {
  READY_FOR_ADMISSION,
  WORKER_REQUIRED,
  POST_ENGINE_VERIFICATION_REQUIRED,
  BLOCKED,
  CORRUPT,
  FOREIGN_OR_CORRUPT,
  LOCAL_IO_ERROR,
  UNSUPPORTED,
  RESTART_REQUIRED,
  FENCED,
};

enum class StartupStepOutcome : uint8_t {
  READY,
  BLOCKED,
  CORRUPT,
  LOCAL_IO_ERROR,
  RESTART_REQUIRED,
  FENCED,
};

struct StartupStepResult {
  StartupStepOutcome outcome{StartupStepOutcome::CORRUPT};
  std::string detail;

  bool ready() const { return outcome == StartupStepOutcome::READY; }
};

struct StartupDeploymentIdentity {
  std::string stream_id;
  std::string server_uuid;
  DeploymentFingerprints fingerprints;
  // SHA-256 over the externally supplied binary/plugin identity used by the
  // local marker. The constituent fingerprints remain in the remote snapshot.
  std::string binary_fingerprint;

  bool operator==(const StartupDeploymentIdentity &) const = default;
};

// Evidence captured while an engine-owning worker has the fresh root open.
// marker_matches and snapshot_matches are required only from the re-exec
// process after the installed root has been activated and its engines opened.
struct StartupRootEvidence {
  Cursor recovered_cursor;
  GtidSetDigest recovered_gtid;
  bool marker_matches{false};
  bool snapshot_matches{false};
  bool server_uuid_matches{false};
  bool configuration_matches{false};
  bool gtid_matches{false};
  bool dd_matches{false};
  bool repository_empty{false};
  bool extent_live_set_matches{false};
  uint64_t exported_extent_count{0};
  std::string exported_extent_set_sha256;
  bool internal_prepared_empty{false};
  bool external_xa_empty{false};
};

// startup_server creates this only after a HEAD-absent initialize-insecure
// child exits cleanly. Its root is the exact root later handed to the export
// worker; neither the coordinator nor the worker may initialize another root.
struct StartupBootstrapPreflight {
  std::filesystem::path root;
  std::string request_nonce;
  std::string request_sha256;
  bool child_exited_cleanly{false};
  // Exact identity observed from the initialized root. The parent cannot know
  // the generated server UUID before initialize-insecure completes.
  StartupDeploymentIdentity initialized_deployment;
  bool dd_initialized{false};
  bool repository_empty{false};
  bool internal_prepared_empty{false};
  bool external_xa_empty{false};
  bool empty_source_scan_stable{false};
  bool old_tc_authority_empty{false};
  bool user_state_empty{false};
  bool legacy_live_extents_empty{false};
};

struct StartupCoordinatorOptions {
  std::filesystem::path target_root;
  MaterializeOptions materialize;
  StartupDeploymentIdentity deployment;
  // A fresh, unpredictable lowercase SHA-256-sized nonce generated by the
  // process adapter. It binds a worker completion to this exact preparation.
  std::string worker_nonce;
  std::optional<StartupBootstrapPreflight> bootstrap_preflight;
};

struct StartupActivationOptions {
  std::filesystem::path target_root;
  StartupDeploymentIdentity deployment;
};

// Cached result of the server hook's mutation-free HEAD-first probe. A
// takeover probe carries the exact HEAD observed before any epoch acquisition;
// a bootstrap probe carries no HEAD identity.
struct StartupHookProbe {
  StartupCoordinatorRoute route{StartupCoordinatorRoute::TAKEOVER};
  PublishedBytes head_object;
  uint64_t head_generation{0};
  Cursor durable_cursor;
};

struct ExactWriterEpoch {
  PublishedBytes object;
  WriterEpoch value;
};

struct PublishedStartupHead {
  PublishedBytes object;
  Head value;
};

struct StartupCandidateBoundary {
  PublishedStartupHead head;
  Cursor replay_exclusive_start;
  Cursor replay_inclusive_end;
};

// This is an owned, bounded cross-process request. The worker exact-reads the
// candidate identified by candidate.head before replay. It opens only root,
// performs route-specific work, exports every snapshot payload under epoch,
// fsyncs those files, captures a FixedSnapshotCut, and exits. It must not
// publish HEAD, install root, open networking, or admit writes.
struct StartupWorkerRequest {
  StartupCoordinatorRoute route{StartupCoordinatorRoute::TAKEOVER};
  std::string request_nonce;
  std::string request_sha256;
  std::filesystem::path root;
  StartupDeploymentIdentity deployment;
  ExactWriterEpoch epoch;
  std::optional<StartupCandidateBoundary> candidate;
  std::optional<MaterializedRoot> materialized;
};

// The parent may construct this only after waitpid reports a clean worker
// exit and its bounded evidence transport has been authenticated. The copied
// FixedSnapshotCut is the only cut publication may consume; it must not be
// resampled after the worker has closed its engines.
struct StartupWorkerCompletion {
  bool child_exited_cleanly{false};
  std::string request_nonce;
  std::string request_sha256;
  StartupRootEvidence root_evidence;
  FixedSnapshotCut snapshot_cut;
};

struct StartupSnapshotPublishRequest {
  StartupCoordinatorRoute route;
  const std::filesystem::path &root;
  const StartupDeploymentIdentity &deployment;
  const ExactWriterEpoch &epoch;
  const StartupRootEvidence &root_evidence;
  const FixedSnapshotCut &snapshot_cut;
  // Non-null for takeover. Publication must use this exact HEAD body and ETag
  // as its parent and must never take a late cursor or engine-state sample.
  const RecoveryPlan *candidate;
};

// Bounded payload written by startup_server to a private sibling file. It is
// deliberately not carried in argv or the environment because canonical GTID
// text can be large. The file is transport-only and is not installed in root.
struct StartupRestartProof {
  StartupCoordinatorRoute route{StartupCoordinatorRoute::TAKEOVER};
  StartupDeploymentIdentity deployment;
  PublishedStartupHead head;
  ExactWriterEpoch epoch;
  LocalInstallMarker marker;
  StartupRootEvidence expected_root;
  // The first manifest is captured immediately after the clean worker exit and
  // rechecked after publication. The second is captured after atomic install;
  // it may differ only by the canonical local install marker.
  StartupStableRootManifest stopped_worker_root;
  StartupStableRootManifest installed_root;
};

// startup_server owns this file. It keeps it through exec, exact-reads and
// authenticates it on re-exec, then unlinks it after the payload is adopted.
// A failed adoption leaves the installed root and first-failure evidence intact.
struct StartupRestartProofReference {
  std::filesystem::path path;
  uint64_t size{0};
  std::string sha256;
};

struct StartupActivationRequest {
  StartupCoordinatorRoute route;
  const RecoveryPlan &published;
  const ExactWriterEpoch &epoch;
  const LocalInstallMarker &marker;
  const StartupRootEvidence &expected_root;
  const StartupStableRootManifest &stopped_worker_root;
  const StartupStableRootManifest &installed_root;
};

struct StartupCoordinatorProof {
  PublishedStartupHead head;
  ExactWriterEpoch epoch;
  LocalInstallMarker marker;
  StartupRootEvidence installed_root;
  StartupStableRootManifest installed_root_manifest;
};

struct StartupCoordinatorResult {
  StartupCoordinatorOutcome outcome{StartupCoordinatorOutcome::CORRUPT};
  std::string detail;
  std::optional<StartupWorkerRequest> worker_request;
  std::optional<StartupRestartProofReference> restart_proof;
  std::optional<StartupCoordinatorProof> proof;

  bool worker_required() const {
    return outcome == StartupCoordinatorOutcome::WORKER_REQUIRED &&
           worker_request.has_value() && !restart_proof.has_value() &&
           !proof.has_value();
  }

  bool restart_required() const {
    return outcome == StartupCoordinatorOutcome::RESTART_REQUIRED &&
           !worker_request.has_value() && restart_proof.has_value() &&
           !proof.has_value();
  }

  bool post_engine_verification_required() const {
    return outcome ==
               StartupCoordinatorOutcome::POST_ENGINE_VERIFICATION_REQUIRED &&
           !worker_request.has_value() && !restart_proof.has_value() &&
           !proof.has_value();
  }

  bool ready_for_admission() const {
    return outcome == StartupCoordinatorOutcome::READY_FOR_ADMISSION &&
           !worker_request.has_value() && !restart_proof.has_value() &&
           proof.has_value();
  }
};

// Canonical, exact-schema documents used by startup_server's private-file
// transport. Parsers reject unknown/duplicate fields, invalid UTF-8, and input
// above the corresponding hard limit. Existing HEAD/WRITER_EPOCH bodies are
// embedded as JSON strings and parsed again against stream on decode.
bool finalize_startup_bootstrap_preflight(
    StartupBootstrapPreflight *value, std::string *error);
bool serialize_startup_bootstrap_preflight(
    const StartupBootstrapPreflight &value, std::string *json,
    std::string *error);
bool parse_startup_bootstrap_preflight(
    std::string_view json, StartupBootstrapPreflight *value,
    std::string *error);
bool finalize_startup_worker_request(const StreamIdentity &stream,
                                     StartupWorkerRequest *value,
                                     std::string *error);
bool serialize_startup_worker_request(const StreamIdentity &stream,
                                      const StartupWorkerRequest &value,
                                      std::string *json, std::string *error);
bool parse_startup_worker_request(const StreamIdentity &stream,
                                  std::string_view json,
                                  StartupWorkerRequest *value,
                                  std::string *error);
bool serialize_startup_worker_completion(
    const StartupWorkerCompletion &value, std::string *json,
    std::string *error);
bool parse_startup_worker_completion(std::string_view json,
                                     StartupWorkerCompletion *value,
                                     std::string *error);
bool serialize_startup_restart_proof(const StreamIdentity &stream,
                                     const StartupRestartProof &value,
                                     std::string *json, std::string *error);
bool parse_startup_restart_proof(const StreamIdentity &stream,
                                 std::string_view json,
                                 StartupRestartProof *value,
                                 std::string *error);
// Canonical digest over the exact ordered immutable extent identities carried
// by a worker cut. Both worker and installed-root evidence bind this digest;
// takeover never compares the new export with the base snapshot live set.
bool startup_extent_set_digest(
    const std::vector<PinnedSmartengineExtent> &extents, uint64_t *count,
    std::string *sha256, std::string *error);

// Operations that require server/runtime integration but never require the
// parent coordinator to own live engine objects. Worker execution and evidence
// collection happen outside this interface.
class StartupCoordinatorOperations {
 public:
  virtual ~StartupCoordinatorOperations() = default;

  virtual StartupStepResult startup_probe(StartupHookProbe *probe) = 0;
  virtual StartupStepResult acquire_epoch(ExactWriterEpoch *epoch) = 0;
  virtual StartupStepResult publish_snapshot(
      const StartupSnapshotPublishRequest &request,
      PublishedStartupHead *published) = 0;
  virtual StartupStepResult persist_restart_proof(
      const StartupRestartProof &proof,
      StartupRestartProofReference *reference) = 0;
  // Called by the re-exec process before stock TC/binlog recovery. It grants
  // only installed-root recovery activation; admission remains closed until
  // finish_post_engine_verification() returns READY_FOR_ADMISSION.
  virtual StartupStepResult activate_installed_root(
      const StartupActivationRequest &request) = 0;
};

// Storage operations are split out so the ordering state machine can be tested
// without an object-store service. The default implementation is the
// production adapter over the bounded reader, fresh-root materializer, and
// crash-safe local installer.
class StartupCoordinatorStorage {
 public:
  virtual ~StartupCoordinatorStorage() = default;

  virtual RecoveryReadResult read(RecoveryPlan *plan) = 0;
  virtual TargetClassification classify(
      const std::filesystem::path &target,
      const LocalInstallMarker &expected_deployment,
      bool allow_managed_replace) = 0;
  virtual MaterializeResult materialize(const RecoveryPlan &plan,
                                        const MaterializeOptions &options,
                                        MaterializedRoot *root) = 0;
  virtual InstallResult install(const std::filesystem::path &temporary_root,
                                const std::filesystem::path &target,
                                const LocalInstallMarker &expected_marker,
                                bool allow_managed_replace) = 0;
  virtual StartupStepResult snapshot_stopped_root(
      const std::filesystem::path &root, StartupRootSnapshot *snapshot) = 0;
};

class DefaultStartupCoordinatorStorage final
    : public StartupCoordinatorStorage {
 public:
  DefaultStartupCoordinatorStorage(ConditionalIo *conditional_io,
                                   PayloadIo *payload_io,
                                   BinlogImageValidator *binlog_validator,
                                   StreamIdentity stream)
      : reader_(conditional_io, std::move(stream)),
        materializer_(payload_io, binlog_validator) {}

  RecoveryReadResult read(RecoveryPlan *plan) override;
  TargetClassification classify(
      const std::filesystem::path &target,
      const LocalInstallMarker &expected_deployment,
      bool allow_managed_replace) override;
  MaterializeResult materialize(const RecoveryPlan &plan,
                                const MaterializeOptions &options,
                                MaterializedRoot *root) override;
  InstallResult install(const std::filesystem::path &temporary_root,
                        const std::filesystem::path &target,
                        const LocalInstallMarker &expected_marker,
                        bool allow_managed_replace) override;
  StartupStepResult snapshot_stopped_root(
      const std::filesystem::path &root,
      StartupRootSnapshot *snapshot) override;

 private:
  RecoveryChainReader reader_;
  RecoveryMaterializer materializer_;
};

class StartupCoordinator {
 public:
  StartupCoordinator(StreamIdentity stream, StartupCoordinatorStorage *storage,
                     StartupCoordinatorOperations *operations)
      : stream_(std::move(stream)),
        storage_(storage),
        operations_(operations) {}

  // Parent phase. Performs HEAD-first preparation and returns one bounded
  // worker request. BOOTSTRAP requires an already completed initialize-insecure
  // preflight; TAKEOVER materializes the exact epoch-bound candidate first.
  StartupCoordinatorResult prepare_worker(
      const StartupCoordinatorOptions &options);

  // Parent phase. Called only after the requested worker exits cleanly. It
  // publishes the worker's exact cut, installs the now-closed stable root,
  // persists a bounded restart proof, and requires exec. It never reopens root.
  StartupCoordinatorResult finish_worker(
      const StartupWorkerCompletion &completion);

  // Re-exec phase, on a fresh coordinator instance. startup_server has already
  // authenticated and parsed the referenced proof. This method exact-rechecks
  // remote HEAD/epoch and the installed marker, then activates root before
  // stock TC/binlog recovery.
  StartupCoordinatorResult adopt_restart_proof(
      const StartupActivationOptions &options,
      const StartupRestartProof &proof);

  // Re-exec post-engine phase. The caller supplies authoritative installed-root
  // evidence only after engines are open. Admission may open only on success.
  StartupCoordinatorResult finish_post_engine_verification(
      const StartupRootEvidence &installed_evidence);

  StartupCoordinatorState state() const { return state_; }
  std::optional<StartupCoordinatorRoute> route() const { return route_; }
  const RecoveryPlan *candidate() const {
    return candidate_.has_value() ? &*candidate_ : nullptr;
  }
  const RecoveryPlan *published() const {
    return published_.has_value() ? &*published_ : nullptr;
  }
  const LocalInstallMarker *installed_marker() const {
    return marker_.has_value() ? &*marker_ : nullptr;
  }

 private:
  StartupCoordinatorResult fail(StartupCoordinatorOutcome outcome,
                                std::string detail);
  StartupCoordinatorResult fail(const StartupStepResult &step,
                                std::string_view operation);

  StreamIdentity stream_;
  StartupCoordinatorStorage *storage_;
  StartupCoordinatorOperations *operations_;
  StartupCoordinatorState state_{StartupCoordinatorState::STARTING};
  std::optional<StartupCoordinatorRoute> route_;
  std::optional<StartupCoordinatorOptions> options_;
  std::optional<StartupActivationOptions> activation_options_;
  std::optional<StartupHookProbe> hook_probe_;
  std::optional<ExactWriterEpoch> acquired_;
  std::optional<RecoveryPlan> candidate_;
  std::optional<MaterializedRoot> materialized_;
  std::optional<StartupRootEvidence> root_evidence_;
  std::optional<RecoveryPlan> published_;
  std::optional<LocalInstallMarker> marker_;
  std::optional<StartupRestartProof> restart_proof_;
  std::optional<StartupStableRootManifest> stopped_worker_root_;
  std::optional<StartupStableRootManifest> installed_root_manifest_;
  bool installed_root_verified_{false};
  std::string worker_nonce_;
  std::string worker_request_sha256_;
};

}  // namespace wesql::remote_commit

#endif  // SQL_REMOTE_COMMIT_STARTUP_COORDINATOR_INCLUDED
